#!/bin/sh

set -e

USER="elasticsearch"
ID="/usr/bin/id"
ADDUSER="/usr/sbin/adduser"
CHOWN="/bin/chown"
INSTALL="/usr/bin/install"

do_configure()
{
    if $ID $USER >/dev/null 2>&1; then
       UID=`$ID --user $USER`
    else
       UID=""
    fi

    if [ "x$UID" = "x" ]; then
        $ADDUSER \
            --system \
            --disabled-password \
            --disabled-login \
            --home /usr/share/elasticsearch \
            --no-create-home \
            --group $USER
    fi

    for d in /var/lib/elasticsearch /var/log/elasticsearch; do
        $INSTALL -d -o $USER -g $USER $d
        $CHOWN -R $USER:$USER $d
    done
}

case "$1" in
    configure)
        do_configure
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
